services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "8080:80"
    container_name: medicine-cabinet-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
